export const FETCH_CHECK_LIST = 'list/FETCH_CHECK_LIST';
export const FETCH_CHECK_LIST_SUCCESS = 'list/FETCH_CHECK_LIST_SUCCESS';
export const FETCH_CHECK_LIST_ERROR = 'list/FETCH_CHECK_LIST_ERROR';

export const FETCH_WEEKLY_CHECK = 'list/FETCH_WEEKLY_CHECK';
export const FETCH_WEEKLY_CHECK_SUCCESS = 'list/FETCH_WEEKLY_CHECK_SUCCESS';
export const FETCH_WEEKLY_CHECK_ERROR = 'list/FETCH_WEEKLY_CHECK_ERROR';
